#Hugo configuration
title = "dede"
baseURL = "https:\/\/widgets.dede.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
galleryChannelIds = "83052333,85595609,85601876"

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = "dede.com"
